language: node_js 
node_js: v10.16.0

os:
  - linux
  - windows

before_install:
  - powershell:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      mkdir nuget;
      Install-Package openssl-vc141-static-x86_64 -RequiredVersion 1.0.2 -Destination nuget;
      fi

install: 
  - npm install -d

script:
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  - slack: merkleblock:ZRA3bl4HQkXwpcZeeRam5RO1
