{
  "os": "linux",
  "dist": "trusty",
  "sudo": false,
  "group": "stable",
  "script": [
    "npm run test"
  ],
  "install": [
    "npm install"
  ],
  "node_js": "v10.8.0",
  "language": "node_js",
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)"
  ],
  "before_install": [
  ]
}
